### ISSUE TITLE
Guia 3 Ejercicio 8

### ISSUE THREAD

**Issue by NaPrado** [POO-ITBA/2024_01#1]
Quisiera saber si es erroneo usar el metodo equals para comparar dos Strings ya que la solucion provista por la catedra usa el metodo compareTo para saber si dos numeros de telefono(Strings) son iguales. Esto se debe a que compareTo es más eficiente o a que se debe? 
Muchas gracias.

**Comment by fmeola** [comment]
Hola @NaPrado. No, para nada. Usar equals está perfecto. En general se usa compareTo porque queremos saber el orden lexicográfico pero comparar compareTo con 0 y usar equals es lo mismo.
