### ISSUE TITLE
TPE Material a entregar .class

### ISSUE THREAD

**Issue by tomaspietravallo** [POO-ITBA/2024_01#37]
Hola buenos dias,

Estábamos comenzando con el TPE y surgió la duda de si:
1. También seria necesario entregar el contenido encontrado en `/out` (archivos `.class`) o si solo el codigo fuente .java.
2. Seria necesario entregar la configuración `.iml` o `/idea` de InteliJ que usamos para configurar JavaFX? Entiendo que no, y asumimos que quien lea/modifique el codigo posee su entorno configurado para el uso de JavaFx, pero prefiero preguntarlo ya que estoy jaja

Saludos
Tomas

**Comment by fmeola** [comment]
Hola @tomaspietravallo 
No, no deben entregar los binarios (.class) ni los archivos de configuración del IDE (.iml, /idea, etc)
