### ISSUE TITLE
TPE Separación front-back con javaFX

### ISSUE THREAD

**Issue by MaximoWehncke** [POO-ITBA/2024_01#39]
Buenas! Tratando de hacer que sea mas orientado a objetos una parte del código fuente, nos surgió la duda de si es mala práctica pasarle a un método de una figura una instancia de un GraphicsContext de JavaFX. Toda esta librería se calificaría como front ?

**Comment by tomaspietravallo** [comment]
En caso de que no se pudieran pasar directamente al backend las propiedades de JavaFX... Estaría bien dentro del modelo MVC tener una clase en el frontend que extienda a la de backend que si accediera a las propiedades de JavaFX?

**Comment by fmeola** [comment]
Sólo vamos a contestar consultas de enunciado. Justamente lo que queremos evaluar es que hagan una correcta separación de front-end y back-end.
@MaximoWehncke Toda la librería de JavaFX califica como front-end.
@tomaspietravallo Así como un método de front-end puede llamar a uno de back-end (pero uno de back no puede llamar a uno de front), una clase de front-end puede extender o componer a una de back (pero no al revés)

**Comment by tomaspietravallo** [comment]
Genial muchas gracias franco.

**Comment by MaximoWehncke** [comment]
Genial Franco, gracias :)
