### ISSUE TITLE
Color defaul Relleno

### ISSUE THREAD

**Issue by NaPrado** [POO-ITBA/2024_01#42]
Al principio del tp se detalla el color que debe tener default es amarillo, luego cuando añadimos la opcion del gradiente mediante dos colores, cuales son los default? amarillo y naranja o ambos amarillos?

**Comment by fmeola** [comment]
Hola @NaPrado 
En 1.4 se indica

> Deberán definir dos colores de relleno por defecto. 

Pueden elegir los colores que ustedes prefieran, pero que sean distintos

**Comment by NaPrado** [comment]
Gracias
