### ISSUE TITLE
Duda sobre Map.Entry<K,V>

### ISSUE THREAD

**Issue by whatisthisgit** [POO-ITBA/2024_01#43]
Hola, queria saber como es posible que se use Map.Entry<K,V> en algunos ejercicios, como el ej 3 en el documento de repaso para el segundo parcial, de tal manera:
```
...

@Override
public K next() {
  while(hasNext()) {
    Map.Entry<K, V> currentEntry = iterator.next();
    if(keyPredicate.test(currentEntry.getKey())) {
      currentValue = currentEntry.getValue();
      return currentEntry.getKey();
    }
  }
  throw new NoSuchElementException();
}

...
```
Ya que es una interfaz. Internamente se usa AbstractMap.SimpleEntry<K, V>?

**Comment by fmeola** [comment]
Hola @whatisthisgit 
En principio no te interesa la clase que implemente esa interfaz (esa es justo una de las ventajas de trabajar con interfaces), vos sabés que vas a poder invocar a getKey y a getValue.
La implementación depende del mapa. En un HashMap se usará java.util.HashMap.Node. En un TreeMap se usará java.util.TreeMap.Entry

**Comment by whatisthisgit** [comment]
Gracias.
