### ISSUE TITLE
TPE - Uso de paquete

### ISSUE THREAD

**Issue by lmoliveto** [POO-ITBA/2024_01#49]
Buenas tardes!
Se puede utilizar el paquete `javafx.geometry` para posicionar elementos?

**Comment by fmeola** [comment]
Hola @lmoliveto 
No, deben hacer las cuentas ustedes

**Comment by tomaspietravallo** [comment]
Hola Franco

Me queda una única duda acerca del paquete, y es su uso por la catedra. Deberíamos modificar el codigo para remover esta librería también?
Archivo: 
### src/frontend/PaintPane.java (codigo original de la catedra)
- Linea 5. 
- Linea 66.

**Comment by fmeola** [comment]
No, para nada. Lo que sea para la ventana, botones, en este caso márgenes, etc está perfecto. Lo que no tienen que hacer es usar clases de JavaFx que eviten usar los métodos de GraphicContext que les dimos

**Comment by tomaspietravallo** [comment]
El uso de Pos.CENTER entonces estaría permitido? Cierto método que refiere al posicionamiento de un javafx.scene.Node toma un javafx.geometry.Pos como argumento...

**Comment by tomaspietravallo** [comment]
Para obtener el posicionamiento deseado si no se puede usar ese método junto con Pos.CENTER hay agregar unos cuantos elementos que hagan de padding al rededor, o sacar las cuentas a mano una vez que toda la app de javafx cargo correctamente, lo cual deja el codigo bastante feo jaja

![613f7923769359d8efef1587a59cbd12](https://github.com/POO-ITBA/2024_01/assets/62444821/bd7fbaa2-3d33-43ba-a39d-b8d49da68ff0)

**Comment by fmeola** [comment]
Sí, por supuesto que lo pueden usar.
Ahí veo que entendí mal la pregunta inicial de @lmoliveto, pensé que se refería a posicionar figuras y no componentes de la ventana de JavaFX. Disculpas por la confusión.

**Comment by tomaspietravallo** [comment]
Jajaj esta bien gracias
