### ISSUE TITLE
TPE-Capas

### ISSUE THREAD

**Issue by NaPrado** [POO-ITBA/2024_01#50]
Buenas, tenemos dudas sobre el comportamiento esperado de la funcionalidad de capas.
1. Se puede crear una figura si se dispone de una capa oculta? En caso de que si, esta debe seguir oculta o no?
2. Entiendo que no pero por las dudas, si una figura esta oculta, esta debe poder dividirse, duplicarse, moverse al centro o modificar alguna de sus propiedades, sea color, sombra o  borde, o ni puede seleccionarse?
3. Si aun una capa no dispone de figuras, seria correcto que por defecto siempre se ofrezca la opcion mostrar, ( Ejemplo inicia en capa 1 y mostrar en true, se prieta en ocultar, luego se cambia de capa a la capa 2 la cual empieza en mostrar, finalmente se vuelve a capa 1,  entonces esta capa debe tener mostrar activado o desactivado? )

**Comment by NaPrado** [comment]
4. Hay que poner un tope?

**Comment by fmeola** [comment]
1. No se especifica, tomen ustedes una decisión
2. No porque no puede solucionarse
3. Tampoco se especifica, tomen ustedes una decisión
4. No

**Comment by NaPrado** [comment]
Oka, Muchas gracias Franco
