### ISSUE TITLE
Duda enunciado Sombra, color y borde

### ISSUE THREAD

**Issue by Iker-Galante** [POO-ITBA/2024_01#53]
En el enunciado dice esto : "Estos controles deben poder modificar la sombra, relleno y borde de figuras ya creadas. En caso de seleccionar una figura en pantalla, los controles deben reflejar las propiedades de sombra, relleno y borde de la figura seleccionada. Al seleccionar una figura si luego se cambia el primer color de relleno en la barra izquierda, se modifica el primer color de relleno de la figura seleccionada. Y en cualquier momento en que se seleccione una figura, el color del borde cambiará a rojo."

Se refiere a que tengo que poder editar una figura que cree sin nada de estas caracteristicas y cambirla a gusto no?

**Comment by fmeola** [comment]
Así es

**Comment by Iker-Galante** [comment]
Otra consulta, no se si me podes tirar un centro pero no estoy pudiendo mostrar en los botones/choiceBox los valores de cada figura al seleccionar , cualquier ayuda es bienvenida

**Comment by fmeola** [comment]
Buscá donde está la lógica que se ejecuta cuando seleccionás una figura y en principio allí deberías actualizar el estado de los botones. Mucho más no puedo decirte.

**Comment by lmoliveto** [comment]
Hola! Si tengo una figura seleccionada, y los estados de los botones son los correspondientes a dicha figura, y luego dejo de seleccionarla (o sea no tengo ninguna figura seleccionada al momento), qué estado se debería mostrar en los botones?

**Comment by fmeola** [comment]
Hola @lmoliveto Pueden mostrar el mismo estado que cuando inician la aplicación de cero. Definan ustedes un valor inicial para todos los controles, los valores que prefieran. Por ejemplo borde en ancho 5 y tipo simple, sombra ninguno, relleno 1 amarillo y relleno 2 naranja.

**Comment by lmoliveto** [comment]
Perfecto, gracias!
