### ISSUE TITLE
TPE - Seleccionar con capas

### ISSUE THREAD

**Issue by lmoliveto** [POO-ITBA/2024_01#58]
Hola! Al oprimir el botón "Seleccionar" estando en la capa 2 por ejemplo, se deberían poder seleccionar sólo las figuras de la capa 2? O se deberían poder seleccionar todas las figuras priorizando las de capas superiores? O no importa qué figura se selecciona, mientras que interseque con el cursor?

**Comment by fmeola** [comment]
La selección de Capa es sólo para poder usar el mostrar/ocultar, no debería importarte en la selección qué capa dice el choicebox de arriba. Si la figura es visible y le pudiste hacer click, entonces seleccioná esa. Si donde hacés click hay una figura en una capa superior y debajo otra figura de una capa inferior desde ya se deberá seleccionar la que está más arriba.

**Comment by lmoliveto** [comment]
Perfecto, gracias!
