### ISSUE TITLE
TPE-Duda Dividir

### ISSUE THREAD

**Issue by Iker-Galante** [POO-ITBA/2024_01#61]
Hola franco, cuando divido ya sea un circulo o elipse o rectangulo o cuadrado no los divido y los dejo una al lado del otro como en el ejemplo. En el cuadrado/rectangulo es uno arriba del otro y para el circulo/elipse esta como en diagonal pasa algo?

**Comment by fmeola** [comment]
No entiendo Iker.
¿Cómo que no los divido? Dividir es no dibujar la figura azul (la dividida) y ahora dibujar dos nuevas figuras (la verde y la amarilla). Las ubicaciones de las figuras verde y amarilla respecto a la ubicación de la azul se indica en el enunciado.

**Comment by Iker-Galante** [comment]
Perdon me mal exprese, lo que quiero decir es que las figuras divididas como por ejemplo la del rectangulo, que las dos figuras resultantes por la division me quedan una encima de la otra en vez de una al lado de la otra

**Comment by fmeola** [comment]
Bueno entonces están haciendo mal las cuentas de los x e y de las nuevas figuras. Si se te solapan un poco por tema de bordes y demás no hay problema pero deben respetar las ubicaciones que ponemos en el enunciado.

**Comment by Iker-Galante** [comment]
Otra duda, para todas las figuras deberan aparecer con la mitad del ancho pero el largo seria lo mismo no?

**Comment by fmeola** [comment]
No Iker. En el enunciado se ve que en el eje X la longitud se reduce a exactamente la mitad. Después en el eje Y tomen una decisión ustedes para lograr un resultado similar a lo pedido en el enunciado.
