### ISSUE TITLE
TPE - duda color sombra

### ISSUE THREAD

**Issue by lucasdicandi** [POO-ITBA/2024_01#62]
![image](https://github.com/POO-ITBA/2024_01/assets/170557930/6fc1df7e-1e74-4c6f-a2e6-1c67728cb14e)
es asi la sombra o deberia ser amarilla en este caso?

**Comment by fmeola** [comment]
La sombra debe usar el primer color de relleno, que veo que es el magenta, así que se ve bien

**Comment by lucasdicandi** [comment]
Perfecto, gracias
