### ISSUE TITLE
TPE - Ancho del borde

### ISSUE THREAD

**Issue by lmoliveto** [POO-ITBA/2024_01#64]
Buenas tardes! Al dibujar las 4 figuras con el mismo ancho de borde, el de la elipse se ve mas finito. Esto puede estar relacionado a cómo javafxá dibuja las elipses? Porque no tiene sentido que pase sólo con la elipse.

<img width="535" alt="image" src="https://github.com/POO-ITBA/2024_01/assets/87945314/a84e441c-d938-4add-b60f-0163adda1572">

**Comment by fmeola** [comment]
Si revisaste los parámetros de strokeOval y el ancho que le mandas es el mismo que el del círculo si podría ser algo de la librería que hay que considerar algo más. No hay problema.
