### ISSUE TITLE
TPE - Uso de optional

### ISSUE THREAD

**Issue by lmoliveto** [POO-ITBA/2024_01#65]
Hola! Al utilizar `Optional<>` el IntelliJ lanza warning. Deberíamos simplemente ignorarlo?

**Comment by fmeola** [comment]
¿Qué warning te tira? Asegurate de no usarlo como tipo de dato de variables de instancia y de no obviar el tipo genérico

**Comment by tomaspietravallo** [comment]
Hola Franco (estoy en el mismo equipo que lu).

Esta siendo utilizado con los tipos genéricos, pero se utiliza para un campo de instancia relevante...

Este campo puede ser null dado que al comienzo de la aplicación el valor no existe (hasta que el usuario luego realice ciertas acciones).... Estaría mal usar `Optional` en este caso? La otra seria siempre poner `if ( x != null )` por varias partes del codigo, en lugar de `ifPresent(x -> ...)`

**Comment by fmeola** [comment]
Claro, a eso iba. Revisá la PPT de la clase extra de Streams donde expliqué Optional. Está también la grabación. La idea es dejar esa variable de instancia como está y que pueda a veces ser nula. El tema es que vos nunca accedés a la variable de instancia directamente, siempre la accedés por un getter (que devuelve Optional)

![Streams en Java](https://github.com/POO-ITBA/2024_01/assets/4400729/c9ae9f2c-fa17-466c-aa0c-62ec5bb4a0d9)

**Comment by tomaspietravallo** [comment]
Perfecto! Muchas gracias
