### ISSUE TITLE
TP- Seleccionar cuando está oculto

### ISSUE THREAD

**Issue by Martin192003** [POO-ITBA/2024_01#69]
Hola profe, 
Quería consultar si, mientras una figura está oculta y, por ejemplo, está tapando a otra figura de otra capa que no está oculta, se tendría que poder seleccionar la de abajo o está bien que no se pueda seleccionar la de abajo porque la está tapando la figura de arriba que está oculta?
Desde ya muchas gracias.

**Comment by fmeola** [comment]
En el canvas si yo como usuario veo una figura y le hago click tengo que poder seleccionarla. No debería ser un impedimento que una figura que yo no veo (porque oculté la capa) esté encima de ella.

**Comment by Martin192003** [comment]
Perfecto, gracias!!
