### ISSUE TITLE
Duda sobre canvasState

### ISSUE THREAD

**Issue by Martin192003** [POO-ITBA/2024_01#70]
Hola profe, 
Quería consultar si el canvasState es totalmente necesario a la hora de hacer la conección entre el backend y el frontend o si se podría quitar. Desde ya muchas gracias.

**Comment by fmeola** [comment]
Es necesario, mantengan el CanvasState. Después es decisión de ustedes qué tanto comportamiento le asignan a esa clase y lo mencionan en el informe

**Comment by fmeola** [comment]
Si te damos clases no esperamos que las elimines por completo, sí que las modifiques, las cambies de paquetes, etc. Por ejemplo no deberías eliminar la clase Rectangle  aunque obviamente podés modificarla. El CanvasState es una clase más

**Comment by Martin192003** [comment]
Perfecto, muchas gracias!
