### ISSUE TITLE
Duda sobre seleccionar

### ISSUE THREAD

**Issue by Martin192003** [POO-ITBA/2024_01#71]
Hola profe, consulta, si selecciono una figura y oprimo el botón de seleccionar de vuelta(es decir se desoprime el botón) el borde de la figura debería cambiarse a negro o debería seguir en rojo, marcando que la figura está seleccionada. Ojalá me haya explciado bien.
Desde ya muchas gracias.

**Comment by fmeola** [comment]
Te explicaste bien. El enunciado no lo indica así que como ustedes prefieran. Basta con que la figura se pueda deseleccionar clickeando un lugar libre en el canvas

**Comment by Martin192003** [comment]
Perfecto profe, muchas gracias!
