### ISSUE TITLE
TPE - Nombre de botón

### ISSUE THREAD

**Issue by lmoliveto** [POO-ITBA/2024_01#76]
Buenas tardes! En una parte del enunciado dice:
<img width="809" alt="image" src="https://github.com/POO-ITBA/2024_01/assets/87945314/fe09b7f5-ea91-44a7-865e-bfa352dbddb7">
por lo que se entiende que el botón debe llamarse "Al centro".

Pero en las imágenes se muestra que el botón se llama "Mov. Centro":
<img width="78" alt="image" src="https://github.com/POO-ITBA/2024_01/assets/87945314/d41ab399-6a87-41a4-b383-18c5a92fb8cd">

Cuál de los dos deberíamos tomar?

**Comment by fmeola** [comment]
Hola @lmoliveto 
Como ustedes prefieran
