### ISSUE TITLE
Entrega del TPE (duda)

### ISSUE THREAD

**Issue by ncanzonieri** [POO-ITBA/2024_01#77]
Profe, descargo el zip del github, veo que el .git está oculto, lo entrego, descargo la entrega y no lo veo en la entrega que descargué. Es normal? Hay que hacer algo especial para descargarlo con .git?

**Comment by ncanzonieri** [comment]
Ahora tampoco lo veo en la descarga del github, tengo que hacer algo en particular para descargarlo con el .git?

**Comment by fmeola** [comment]
Hola @ncanzonieri 
Usando el botón de descarga de la web de GitHub nunca vas a obtener el directorio .git/
Necesitás hacer el zip sobre tu repositorio local (sobre tu .git/ local) o de otro integrante del grupo

**Comment by ncanzonieri** [comment]
Ok, gracias, hice una segunda entrega que era un comprimido del local.

**Comment by ncanzonieri** [comment]
Puede ser igual que cuando descargo la entrega, en el comprimido que descargo no esté? Pasa que quiero corroborar que se envió bien

**Comment by fmeola** [comment]
No, debería estar.

**Comment by ncanzonieri** [comment]
Ah ya entendí mi confusión, cuando se hace una nueva entrega, campus le pone de nombre "Intento 1". Estaba constantemente comprobando la primer entrega pensando que era la última porque campus la llamaba como tal. Parece que cuando campus muestra las entregas las numera al revés, pero después las muestra con la numeración correcta al abrirlos.
![image](https://github.com/POO-ITBA/2024_01/assets/149270345/c755fc36-9859-4f76-b682-87897eba86d0)
![image](https://github.com/POO-ITBA/2024_01/assets/149270345/4d53b91b-c46f-490a-8ba9-c8011bbb94a9)

**Comment by fmeola** [comment]
Que inconsistencia. Bueno bien que te diste cuenta.
